# Generated by Django 2.1.1 on 2018-09-08 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
