# Generated by Django 2.1.1 on 2018-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='career',
            field=models.CharField(default='No especifica carrera', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viaje',
            name='destination',
            field=models.TextField(default='No especifica destino'),
            preserve_default=False,
        ),
    ]
