# Generated by Django 2.1.1 on 2018-09-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20180915_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destination',
            field=models.CharField(max_length=140),
        ),
    ]
