# Generated by Django 2.1.1 on 2018-09-21 17:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_auto_20180915_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='date',
            new_name='departureDate',
        ),
        migrations.AddField(
            model_name='viaje',
            name='eventUrl',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='viaje',
            name='returnDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='career',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
