# Generated by Django 2.1.1 on 2018-09-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20180921_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='description',
            new_name='longDescription',
        ),
        migrations.AddField(
            model_name='viaje',
            name='shortDescription',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='viaje',
            name='eventUrl',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
