# Generated by Django 2.1.1 on 2018-09-23 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_auto_20180921_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('text', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='viajes.Viaje')),
            ],
        ),
    ]
