# Generated by Django 2.1.1 on 2018-09-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='career',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='destination',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='shortDescription',
            field=models.CharField(max_length=140),
        ),
    ]
